### PR TITLE
Make spans tested for Kafka integration test deterministic

### LINKED ISSUE #2304: Flaky Kafka integration test
* https://github.com/open-telemetry/opentelemetry-go-instrumentation/actions/runs/14977193023/job/42072397106
* https://github.com/open-telemetry/opentelemetry-go-instrumentation/actions/runs/14977191615/job/42072399970
* https://github.com/open-telemetry/opentelemetry-go-instrumentation/actions/runs/14977086887/job/42072051680
* https://github.com/open-telemetry/opentelemetry-go-instrumentation/actions/runs/14976851558/job/42071242684
* https://github.com/open-telemetry/opentelemetry-go-instrumentation/actions/runs/14976131057/job/42068844828
* https://github.com/open-telemetry/opentelemetry-go-instrumentation/actions/runs/14976118723/job/42068804358
* ...

```terminal
# ...
=== RUN   TestIntegration/ResourceAttribute/ServiceName
=== RUN   TestIntegration/Scope/0
=== RUN   TestIntegration/Scope/1
=== RUN   TestIntegration/ProducerSpan/0
=== RUN   TestIntegration/ProducerSpan/1
=== RUN   TestIntegration/ConsumerSpan/0
=== NAME  TestIntegration
    integration_test.go:60: 
        	Error Trace:	/__w/opentelemetry-go-instrumentation/opentelemetry-go-instrumentation/internal/test/e2e/kafka-go/integration_test.go:60
        	Error:      	Not equal: 
        	            	expected: "ba530d9a1457a50120092758e0b083b3"
        	            	actual  : "fc92d3139ed1045f78eddf511a20bd74"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-ba530d9a1457a50120092758e0b083b3
        	            	+fc92d3139ed1045f78eddf511a20bd74
        	Test:       	TestIntegration
        	Messages:   	Span 3: trace ID
=== RUN   TestIntegration/ConsumerSpan/1
=== NAME  TestIntegration
    integration_test.go:60: 
        	Error Trace:	/__w/opentelemetry-go-instrumentation/opentelemetry-go-instrumentation/internal/test/e2e/kafka-go/integration_test.go:60
        	Error:      	Not equal: 
        	            	expected: "ba530d9a1457a50120092758e0b083b3"
        	            	actual  : "90ee8743798a720408b8ccdff185226f"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-ba530d9a1457a50120092758e0b083b3
        	            	+90ee8743798a720408b8ccdff185226f
        	Test:       	TestIntegration
        	Messages:   	Span 4: trace ID
=== RUN   TestIntegration/ConsumerSpan/2
    integration_test.go:159: 
        	Error Trace:	/__w/opentelemetry-go-instrumentation/opentelemetry-go-instrumentation/internal/test/e2e/kafka-go/integration_test.go:159
        	Error:      	Not equal: 
        	            	expected: "topic1 receive"
        	            	actual  : " receive"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-topic1 receive
        	            	+ receive
        	Test:       	TestIntegration/ConsumerSpan/2
        	Messages:   	span name
    integration_test.go:168: 
        	Error Trace:	/__w/opentelemetry-go-instrumentation/opentelemetry-go-instrumentation/internal/test/e2e/kafka-go/integration_test.go:168
        	Error:      	Not equal: 
        	            	expected: "topic1"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-topic1
        	            	+
        	Test:       	TestIntegration/ConsumerSpan/2
        	Messages:   	messaging.destination.name
    integration_test.go:174: 
        	Error Trace:	/__w/opentelemetry-go-instrumentation/opentelemetry-go-instrumentation/internal/test/e2e/kafka-go/integration_test.go:174
        	Error:      	Not equal: 
        	            	expected: "key1"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-key1
        	            	+
        	Test:       	TestIntegration/ConsumerSpan/2
        	Messages:   	messaging.kafka.message.key
--- FAIL: TestIntegration (46.59s)
    --- PASS: TestIntegration/ResourceAttribute/ServiceName (0.00s)
    --- PASS: TestIntegration/Scope/0 (0.00s)
    --- PASS: TestIntegration/Scope/1 (0.00s)
    --- PASS: TestIntegration/ProducerSpan/0 (0.00s)
    --- PASS: TestIntegration/ProducerSpan/1 (0.00s)
    --- PASS: TestIntegration/ConsumerSpan/0 (0.00s)
    --- PASS: TestIntegration/ConsumerSpan/1 (0.00s)
    --- FAIL: TestIntegration/ConsumerSpan/2 (0.00s)
FAIL
exit status 1
FAIL	go.opentelemetry.io/auto/internal/test/e2e/kafka-go	46.627s
```

### PR DESCRIPTION
**Pull request by MrAlias**
Fix #2304

Ensure the expected spans are generated when the application runs. Then, ensure that only those spans are validated. Leave any extraneous spans (i.e. from setup) untested.

- Update the testing application to ensure both topic writes are read
- Refactor the Kafka setup code to its own function
- Update the integration tests to validate each expected span deterministically based on its name and kind
- Stop using regex to validate as we deterministically know what we are looking for

Local testing and multiple runs with the CI system indicate this has resolved #2304 as best as I can tell.

### CODE REVIEW

File: internal/test/e2e/kafka-go/integration_test.go [hunk 1]
```diff
@@ -39,103 +38,73 @@ func TestIntegration(t *testing.T) {
...
-			assert.Equal(t, scopeName, scope.Scope().Name(), "scope name")
-			assert.Equal(t, semconv.SchemaURL, scope.SchemaUrl(), "schema URL")
-
-			scope.Spans().MoveAndAppendTo(spans)
-		})
-	}
-
 	// All trace ID should be the same.
-	tIDBytes := [16]byte(spans.At(0).TraceID())
+	tIDBytes := [16]byte(scopes[0].Spans().At(0).TraceID())
```
Comment (grcevski) [inline internal/test/e2e/kafka-go/integration_test.go:42]: Do we want to test here that scopes is at least of length 1?

**Review by grcevski — APPROVED** [review]
LGTM!

File: internal/test/e2e/kafka-go/integration_test.go (hunk 1 above)
Comment (MrAlias) [reply internal/test/e2e/kafka-go/integration_test.go:42]: That is done above: https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/2310/files#diff-3848f90b432570be66c7b04a0af9ec19c43b228a964bc41ab6f0c63beccea0b2R33

Not the most obvious in my opinion, but our linting likes to use `NotEmtpy(/* ... */)` over `Len(0, spans)`. :shrug:
